# Site settings
title: Gaussian Process and Uncertainty Quantification Summer School, 2016
email: 
description: > # this means to ignore newlines until "baseurl:"
  This GP Summer School will focus on Gaussian processes and Uncertainty Quantificiation. It will take place in Sheffield, UK from 12th to 15th of September 2016
permalink: "/:categories/:title.html"
banner: sestri.jpeg

baseurl: "/gpuqss16" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site

conference:
  room: PLB-DS05, Pam Liversidge Building 
  venue: University of Sheffield
  location: Sheffield, UK
  registration_url: "https://onlineshop.shef.ac.uk/browse/extra_info.asp?compid=1&modid=2&deptid=8&catid=39&prodid=411"
  mapbox:
    latitude: 53.3819
    longitude: -1.4793
    map_id: lawrennd.pnc4gglp
    access_token: "pk.eyJ1IjoibGF3cmVubmQiLCJhIjoiY2luNmUyN2psMDB2MXdlbTJib3dmM3BsOSJ9.OpJ8Nc0xOGyNKZtAAsLECQ"
    zoom_level: 17
  year: 2016
  month: September
  dates:
  - 2016-09-12
  - 2016-09-13
  - 2016-09-14
  - 2016-09-15
  draft: True # set to True if the programme is draft only.
  name: GPSS 2016 - Gaussian Processes and Uncertainty Quantification Summer School
  hosts:
  organizers:
  - {name: Javier Gonzalez, url: "http://javiergonzalezh.github.io/"}
  - {name: Richard Wilkinson, url: "http://r-wilkinson.staff.shef.ac.uk/"}
  - {name: Jeremy Oakley, url: "http://www.jeremy-oakley.staff.shef.ac.uk/"}
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Sheffield ML Group, url: "http://sheffieldml.github.io"}
  name: Gaussian Process and Uncertainty Quantification Summer School
  

twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool
analytics:
  google:
    tracking_id: UA-62991754-1

youtube:
  height: 315
  width: 560

future: true
