# Site settings
title: Gaussian Process and Uncertainty Quantification Summer School, 2016
email:
description: > # this means to ignore newlines until "baseurl:"
  The 2016 GP Summer School will focus on Gaussian processes and Uncertainty Quantification. It will take place in Sheffield, UK from 12th to 15th of September 2016. 
permalink: "/:categories/:title.html"
banner:

baseurl: "/gpuqss16" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: lawrennd/proceedings
style: gpss

conference:
  room: "PLB-DS05, Pam Liversidge Building"
  venue: University of Sheffield
  location: Sheffield, UK
  registration_url: # to appear "https://onlineshop.shef.ac.uk/browse/extra_info.asp?compid=1&modid=2&deptid=8&catid=39&prodid=411"
  year: 2016
  month: September
  dates:
  - 2016-09-12
  - 2016-09-13
  - 2016-09-14
  - 2016-09-15
  draft: False # set to true if the programme is draft only.
  full_name: Gaussian Processes and Uncertainty Quantification Summer School
  short_name: GPSS
  name: Gaussian Process Summer School 
  hosts:
  chairs:
  - type: Organizers
    people:
    - {given: Javier, family: Gonzalez, url: "http://javiergonzalezh.github.io/"}
    - {given: Richard, family: Wilkinson, url: "http://r-wilkinson.staff.shef.ac.uk/"}
    - {given: Jeremy, family: Oakley, url: "http://www.jeremy-oakley.staff.shef.ac.uk/"}
    - {given: Neil D., family: Lawrence, url: "http://inverseprobability.com"}
    - {given: Sheffield ML Group, url: "http://sheffieldml.github.io"}
  sponsors: 
  - name: The Open Data Science Initiative
    url: http://opendsi.cc

map:
  show: True
  mapbox:
    latitude: 53.3819
    longitude: -1.4793
    map_id: lawrennd.pnc4gglp
    access_token: "pk.eyJ1IjoibGF3cmVubmQiLCJhIjoiY2luNmUyN2psMDB2MXdlbTJib3dmM3BsOSJ9.OpJ8Nc0xOGyNKZtAAsLECQ"
    zoom_level: 17
    width: 100%
    height: 500px

twitter_username: datascienceshef
github_username:  gpschool
facebook_page: gaussianprocesssummerschool
analytics:
  google:
    tracking_id: UA-62991754-1

youtube:
  height: 315
  width: 560

ghub:
  edit: true
  repository: gpuqss16
  
previous_meeting:
  name: Previous School
  url: "http://gpss.cc/gpss15"

future: true
