# Site settings
title: Gaussian Process and Uncertainty Quantification Summer School, 2016
venue: Sheffield, UK
email: 
description: > # this means to ignore newlines until "baseurl:"
  The 2016 Gaussian Process and Uncertainty Quantification Summer School held at the University of Sheffield.
permalink: "/:categories/:title.html"
banner: sestri.jpeg
  location: Sheffield, UK
  year: 2016
  month: September
  dates:
  - 2016-09-12
  - 2016-09-13
  - 2016-09-14
  - 2016-09-15
  draft: True # set to True if the programme is draft only.

baseurl: "/gpuqss16" # the subpath of your site, e.g. /blog/
url: "http://gpss.cc" # the base hostname & protocol for your site

conference:
  name: GPSS 2016 - Gaussian Processes and Uncertainty Quantification Summer School
  hosts:
  organizers:
  - {name: Neil Lawrence, url: "http://inverseprobability.com"}
  - {name: Richard Wilkinson, url: "http://r-wilkinson.staff.shef.ac.uk/"}
  - {name: Jeremy Oakley, url: "http://www.jeremy-oakley.staff.shef.ac.uk/"}
  - {name: Javier Gonzalez, url: "http://javiergonzalezh.github.io/"}
  - {name: Sheffield ML Group, url: "http://sheffieldml.github.io"}
  name: Gaussian Process and Uncertainty Quantification Summer School
  location: Pam Liversidge Building, PLB-DS05, University of Sheffield, UK
  year: 2016
  month: September
  dates:
  - {date: 12, day: Monday, month: September, year: 2016}
  - {date: 13, day: Tuesday, month: September, year: 2016}
  - {date: 14, day: Wednesday, month: September, year: 2016}
  - {date: 15, day: Thursday, month: September, year: 2016}
  draft: Y # set to Y if the programme is draft only.
  
# Build settings
markdown: kramdown




twitter_username: datascienceshef
github_username:  SheffieldML
facebook_page: gaussianprocesssummerschool
analytics:
  google:
    tracking_id: UA-62991754-1

youtube:
  height: 315
  width: 560
future: true

# Build settings
markdown: kramdown
